### ISSUE TITLE
Add log file path/troubleshooting info to Readme

### ISSUE THREAD

**Issue by budak7273** [super-miner/Core-Launcher#24]
You mentioned on the [discord](https://discord.com/channels/851842678340845600/1173510418690490458/1293307151821049887) that logs are at `AppData\Roaming\Godot\app_userdata\Core Launcher (An Unofficial Launcher for Core Keeper)\logs`. This info should be mentioned in the readme. Additional troubleshooting info would also be beneficial.

**Comment by super-miner** [comment]
Done
